### PR TITLE
BOM-2952: Replace travis with GitHub CI

### PR DESCRIPTION
**Pull request by UsamaSadiq**

### CODE REVIEW

**Comment by UsamaSadiq** [comment]
Hi @nedbat , I've switched the repo from `coveralls` to use `coverage` but the step to push coverage check is failing. Could you help out in fixing this check? https://app.codecov.io/gh/edx/+?search=ccx-keys shows that the repo hasn't been setup yet. I've tried to setup the repo but for some reason, it isn't getting enabled.

**Comment by nedbat** [comment]
I experimented with the XBlock repo (which had successful codecov uploads).  v2 of the uploader needs a file created that v1 would create automatically.  Here's the XBlock fix:  https://github.com/edx/XBlock/pull/560

**Comment by UsamaSadiq** [comment]
@nedbat could you please also remove the required Travis check from the repo settings? Thanks.

**Comment by nedbat** [comment]
@UsamaSadiq done

**Review by nedbat — APPROVED** [review]

**Pull request merged**
